# Very lightweight combat log
combatlog:
  enabled: true
  disable-elytra: true # Disable elytra in combat
  cooldowns: # Cooldowns to apply in combat
    TRIDENT: # Item names in this config use https: //hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      duration: 100 # In ticks
      global: false # True = cooldowns also applies outside of combat
      nbt:
        enchantments:
          riptide: 1
    TRIDENT:
      duration: 200
      global: false
      nbt:
        enchantments:
          riptide: 2
    TRIDENT:
      duration: 300
      global: false
      nbt:
        enchantments:
          riptide: 3
    ENDER_PEARL:
      duration: 40
      global: false
    ENDER_PEARL:
      duration: 20
      global: true
    CHORUS_FRUIT:
      duration: 200
      global: true
    WIND_CHARGE:
      duration: 40
      global: true

# Whether to drop player heads on death
death-drops:
  enabled: true

# Disable specific effects from being inflicted onto *players*
disabled-potions:
  enabled: true
  effects: # https: //hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
    WEAKNESS: 0 # Maximum allowed level
    SLOW_FALLING: 0

# Disallow specific enchantments on specific items
restricted-enchantments:
  enabled: true
  items: # Priority goes down the list
    MACE: # Item names are inclusive, ie HELMET will apply to every item with helmet in its name
      glint: false # Whether or not to show the enchantment glint
      enchantments:
        DENSITY: 0 # Maximum allowed level
        BREACH: 0
        WIND_BURST: 0
    ELYTRA:
      glint: true
      enchantments:
        MENDING: 0
    GLOBAL: # Global config should be the lowest priority
      glint: true
      enchantments:
        VANISHING_CURSE: 0

# Reduce explosion damage per item
explosion-damage: # Applies before armour damage reduction calculation
  enabled: true
  bed: 0.25 # Multiplier is applied before armour, make sure to check damage in game
  anchor: 0.25
  cart: 0.4
  crystal: 0.25

# System set in place to limit the maximum amount of items players can carry
# When the item limit is exceeded, apply effects to the player
item-limits:
  enabled: true
  scan-bundles: true
  scan-shulkers: false
  scan-echest: false
  message-type: ACTION_BAR # ACTION_BAR or TITLE
  text: "You are overencumbered and cannot run!"
  subtitle: "Drop excess items to move" # Only used if message-type is TITLE
  items:
    TOTEM_OF_UNDYING: 1
    ENDER_PEARL: 32
    COBWEB: 64
    EXPERIENCE_BOTTLE: 128
    TURTLE_MASTER: 1 # Potions are added with their PotionEffectType name
  groups: # For example, you don't want players to bypass the item cap by carrying breeze rods to craft into wind charges
    wind_items: # Name groups whatever you want
      limit: 64
      items:
        WIND_CHARGE: 1 # See how awesome this is?
        BREEZE_ROD: 4
  effects: # Effects to apply to encumbered players
    BLINDNESS:
      duration: 40 # In ticks!
      amplifier: 3
    SLOWNESS:
      duration: 40
      amplifier: 3
    WEAKNESS:
      duration: 40
      amplifier: 1